use f1;
CREATE TABLE circuit(
   circuitId INTEGER PRIMARY KEY  auto_increment
  ,name      VARCHAR(70) NOT NULL
  ,location  VARCHAR(30) NOT NULL
  ,country   VARCHAR(50) NOT NULL
);
INSERT INTO circuit(circuitId,name,location,country) VALUES (1,'Albert Park Grand Prix Circuit','Melbourne','Australia');
INSERT INTO circuit(circuitId,name,location,country) VALUES (2,'Sepang International Circuit','Kuala Lumpur','Malaysia');
INSERT INTO circuit(circuitId,name,location,country) VALUES (3,'Bahrain International Circuit','Sakhir','Bahrain');
INSERT INTO circuit(circuitId,name,location,country) VALUES (4,'Circuit de Barcelona-Catalunya','Montmeló','Spain');
INSERT INTO circuit(circuitId,name,location,country) VALUES (5,'Istanbul Park','Istanbul','Turkey');
INSERT INTO circuit(circuitId,name,location,country) VALUES (6,'Circuit de Monaco','Monte-Carlo','Monaco');
INSERT INTO circuit(circuitId,name,location,country) VALUES (7,'Circuit Gilles Villeneuve','Montreal','Canada');
INSERT INTO circuit(circuitId,name,location,country) VALUES (8,'Circuit de Nevers Magny-Cours','Magny Cours','France');
INSERT INTO circuit(circuitId,name,location,country) VALUES (9,'Silverstone Circuit','Silverstone','UK');
INSERT INTO circuit(circuitId,name,location,country) VALUES (10,'Hockenheimring','Hockenheim','Germany');
INSERT INTO circuit(circuitId,name,location,country) VALUES (11,'Hungaroring','Budapest','Hungary');
INSERT INTO circuit(circuitId,name,location,country) VALUES (12,'Valencia Street Circuit','Valencia','Spain');
INSERT INTO circuit(circuitId,name,location,country) VALUES (13,'Circuit de Spa-Francorchamps','Spa','Belgium');
INSERT INTO circuit(circuitId,name,location,country) VALUES (14,'Autodromo Nazionale di Monza','Monza','Italy');
INSERT INTO circuit(circuitId,name,location,country) VALUES (15,'Marina Bay Street Circuit','Marina Bay','Singapore');
INSERT INTO circuit(circuitId,name,location,country) VALUES (16,'Fuji Speedway','Oyama','Japan');
INSERT INTO circuit(circuitId,name,location,country) VALUES (17,'Shanghai International Circuit','Shanghai','China');
INSERT INTO circuit(circuitId,name,location,country) VALUES (18,'Autódromo José Carlos Pace','São Paulo','Brazil');
INSERT INTO circuit(circuitId,name,location,country) VALUES (19,'Indianapolis Motor Speedway','Indianapolis','USA');
INSERT INTO circuit(circuitId,name,location,country) VALUES (20,'Nürburgring','Nürburg','Germany');
INSERT INTO circuit(circuitId,name,location,country) VALUES (21,'Autodromo Enzo e Dino Ferrari','Imola','Italy');
INSERT INTO circuit(circuitId,name,location,country) VALUES (22,'Suzuka Circuit','Suzuka','Japan');
INSERT INTO circuit(circuitId,name,location,country) VALUES (80,'Las Vegas Strip Street Circuit','Las Vegas','United States');
INSERT INTO circuit(circuitId,name,location,country) VALUES (24,'Yas Marina Circuit','Abu Dhabi','UAE');
INSERT INTO circuit(circuitId,name,location,country) VALUES (25,'Autódromo Juan y Oscar Gálvez','Buenos Aires','Argentina');
INSERT INTO circuit(circuitId,name,location,country) VALUES (26,'Circuito de Jerez','Jerez de la Frontera','Spain');
INSERT INTO circuit(circuitId,name,location,country) VALUES (27,'Autódromo do Estoril','Estoril','Portugal');
INSERT INTO circuit(circuitId,name,location,country) VALUES (28,'Okayama International Circuit','Okayama','Japan');
INSERT INTO circuit(circuitId,name,location,country) VALUES (29,'Adelaide Street Circuit','Adelaide','Australia');
INSERT INTO circuit(circuitId,name,location,country) VALUES (30,'Kyalami','Midrand','South Africa');
INSERT INTO circuit(circuitId,name,location,country) VALUES (31,'Donington Park','Castle Donington','UK');
INSERT INTO circuit(circuitId,name,location,country) VALUES (32,'Autódromo Hermanos Rodríguez','Mexico City','Mexico');
INSERT INTO circuit(circuitId,name,location,country) VALUES (33,'Phoenix street circuit','Phoenix','USA');
INSERT INTO circuit(circuitId,name,location,country) VALUES (34,'Circuit Paul Ricard','Le Castellet','France');
INSERT INTO circuit(circuitId,name,location,country) VALUES (35,'Korean International Circuit','Yeongam County','Korea');
INSERT INTO circuit(circuitId,name,location,country) VALUES (36,'Autódromo Internacional Nelson Piquet','Rio de Janeiro','Brazil');
INSERT INTO circuit(circuitId,name,location,country) VALUES (37,'Detroit Street Circuit','Detroit','USA');
INSERT INTO circuit(circuitId,name,location,country) VALUES (38,'Brands Hatch','Kent','UK');
INSERT INTO circuit(circuitId,name,location,country) VALUES (39,'Circuit Park Zandvoort','Zandvoort','Netherlands');
INSERT INTO circuit(circuitId,name,location,country) VALUES (40,'Zolder','Heusden-Zolder','Belgium');
INSERT INTO circuit(circuitId,name,location,country) VALUES (41,'Dijon-Prenois','Dijon','France');
INSERT INTO circuit(circuitId,name,location,country) VALUES (42,'Fair Park','Dallas','USA');
INSERT INTO circuit(circuitId,name,location,country) VALUES (43,'Long Beach','California','USA');
INSERT INTO circuit(circuitId,name,location,country) VALUES (44,'Las Vegas Street Circuit','Nevada','USA');
INSERT INTO circuit(circuitId,name,location,country) VALUES (45,'Jarama','Madrid','Spain');
INSERT INTO circuit(circuitId,name,location,country) VALUES (46,'Watkins Glen','New York State','USA');
INSERT INTO circuit(circuitId,name,location,country) VALUES (47,'Scandinavian Raceway','Anderstorp','Sweden');
INSERT INTO circuit(circuitId,name,location,country) VALUES (48,'Mosport International Raceway','Ontario','Canada');
INSERT INTO circuit(circuitId,name,location,country) VALUES (49,'Montjuïc','Barcelona','Spain');
INSERT INTO circuit(circuitId,name,location,country) VALUES (50,'Nivelles-Baulers','Brussels','Belgium');
INSERT INTO circuit(circuitId,name,location,country) VALUES (51,'Charade Circuit','Clermont-Ferrand','France');
INSERT INTO circuit(circuitId,name,location,country) VALUES (52,'Circuit Mont-Tremblant','Quebec','Canada');
INSERT INTO circuit(circuitId,name,location,country) VALUES (53,'Rouen-Les-Essarts','Rouen','France');
INSERT INTO circuit(circuitId,name,location,country) VALUES (54,'Le Mans','Le Mans','France');
INSERT INTO circuit(circuitId,name,location,country) VALUES (55,'Reims-Gueux','Reims','France');
INSERT INTO circuit(circuitId,name,location,country) VALUES (56,'Prince George Circuit','Eastern Cape Province','South Africa');
INSERT INTO circuit(circuitId,name,location,country) VALUES (57,'Zeltweg','Styria','Austria');
INSERT INTO circuit(circuitId,name,location,country) VALUES (58,'Aintree','Liverpool','UK');
INSERT INTO circuit(circuitId,name,location,country) VALUES (59,'Circuito da Boavista','Oporto','Portugal');
INSERT INTO circuit(circuitId,name,location,country) VALUES (60,'Riverside International Raceway','California','USA');
INSERT INTO circuit(circuitId,name,location,country) VALUES (61,'AVUS','Berlin','Germany');
INSERT INTO circuit(circuitId,name,location,country) VALUES (62,'Monsanto Park Circuit','Lisbon','Portugal');
INSERT INTO circuit(circuitId,name,location,country) VALUES (63,'Sebring International Raceway','Florida','USA');
INSERT INTO circuit(circuitId,name,location,country) VALUES (64,'Ain Diab','Casablanca','Morocco');
INSERT INTO circuit(circuitId,name,location,country) VALUES (65,'Pescara Circuit','Pescara','Italy');
INSERT INTO circuit(circuitId,name,location,country) VALUES (66,'Circuit Bremgarten','Bern','Switzerland');
INSERT INTO circuit(circuitId,name,location,country) VALUES (67,'Circuit de Pedralbes','Barcelona','Spain');
INSERT INTO circuit(circuitId,name,location,country) VALUES (68,'Buddh International Circuit','Uttar Pradesh','India');
INSERT INTO circuit(circuitId,name,location,country) VALUES (69,'Circuit of the Americas','Austin','USA');
INSERT INTO circuit(circuitId,name,location,country) VALUES (70,'Red Bull Ring','Spielberg','Austria');
INSERT INTO circuit(circuitId,name,location,country) VALUES (71,'Sochi Autodrom','Sochi','Russia');
INSERT INTO circuit(circuitId,name,location,country) VALUES (73,'Baku City Circuit','Baku','Azerbaijan');
INSERT INTO circuit(circuitId,name,location,country) VALUES (75,'Autódromo Internacional do Algarve','Portimão','Portugal');
INSERT INTO circuit(circuitId,name,location,country) VALUES (76,'Autodromo Internazionale del Mugello','Mugello','Italy');
INSERT INTO circuit(circuitId,name,location,country) VALUES (77,'Jeddah Corniche Circuit','Jeddah','Saudi Arabia');
INSERT INTO circuit(circuitId,name,location,country) VALUES (78,'Losail International Circuit','Al Daayen','Qatar');
INSERT INTO circuit(circuitId,name,location,country) VALUES (79,'Miami International Autodrome','Miami','USA');